/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package carrentapplication.view;

import com.raven.main.Main;

/**
 *
 * @author Manidu
 */
public class AdminPanel extends javax.swing.JPanel {

    /**
     * Creates new form AdminPanel
     */
    public AdminPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bookingButton = new javax.swing.JButton();
        customersButton = new javax.swing.JButton();
        carsButton = new javax.swing.JButton();
        adminButton = new javax.swing.JButton();
        carTypeButton = new javax.swing.JButton();
        homepageButton = new javax.swing.JButton();
        rentalDetailButton = new javax.swing.JButton();
        detailPanel = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jPanel2.setBackground(new java.awt.Color(153, 0, 255));

        bookingButton.setBackground(new java.awt.Color(255, 102, 102));
        bookingButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bookingButton.setForeground(new java.awt.Color(0, 0, 0));
        bookingButton.setText("Borrow Car");
        bookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingButtonActionPerformed(evt);
            }
        });

        customersButton.setBackground(new java.awt.Color(255, 102, 102));
        customersButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        customersButton.setForeground(new java.awt.Color(0, 0, 0));
        customersButton.setText("Customers");
        customersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customersButtonActionPerformed(evt);
            }
        });

        carsButton.setBackground(new java.awt.Color(255, 102, 102));
        carsButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        carsButton.setForeground(new java.awt.Color(0, 0, 0));
        carsButton.setText("Cars");
        carsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carsButtonActionPerformed(evt);
            }
        });

        adminButton.setBackground(new java.awt.Color(255, 102, 102));
        adminButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        adminButton.setForeground(new java.awt.Color(0, 0, 0));
        adminButton.setText("Admin");

        carTypeButton.setBackground(new java.awt.Color(255, 102, 102));
        carTypeButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        carTypeButton.setForeground(new java.awt.Color(0, 0, 0));
        carTypeButton.setText("Car Type");
        carTypeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                carTypeButtonActionPerformed(evt);
            }
        });

        homepageButton.setBackground(new java.awt.Color(255, 102, 102));
        homepageButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        homepageButton.setForeground(new java.awt.Color(0, 0, 0));
        homepageButton.setText("Home Page");
        homepageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homepageButtonActionPerformed(evt);
            }
        });

        rentalDetailButton.setBackground(new java.awt.Color(255, 102, 102));
        rentalDetailButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        rentalDetailButton.setForeground(new java.awt.Color(0, 0, 0));
        rentalDetailButton.setText("RentalDetail");
        rentalDetailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentalDetailButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(carTypeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(adminButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customersButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(carsButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(homepageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rentalDetailButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookingButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addComponent(carTypeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(carsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(customersButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bookingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(homepageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(adminButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(rentalDetailButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        detailPanel.setBackground(new java.awt.Color(0, 0, 0));
        detailPanel.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 968, Short.MAX_VALUE)
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void customersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customersButtonActionPerformed
          customerPanel();
    }//GEN-LAST:event_customersButtonActionPerformed

    private void carsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carsButtonActionPerformed
        carsPanel();
    }//GEN-LAST:event_carsButtonActionPerformed

    private void carTypeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_carTypeButtonActionPerformed
          carTypePanel();
    }//GEN-LAST:event_carTypeButtonActionPerformed

    private void homepageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homepageButtonActionPerformed
     //  loadHomePage();
       
    }//GEN-LAST:event_homepageButtonActionPerformed

    private void bookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingButtonActionPerformed
          bookingPanel();
    }//GEN-LAST:event_bookingButtonActionPerformed

    private void rentalDetailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentalDetailButtonActionPerformed
          //       this.setVisible(false);
                 ViewNavigator.getInstance().disposeAdminFrame();
                 ViewNavigator.getInstance().setChartFrame(new Main());
                 ViewNavigator.getInstance().visibleChartFrame();
    }//GEN-LAST:event_rentalDetailButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adminButton;
    private javax.swing.JButton bookingButton;
    private javax.swing.JButton carTypeButton;
    private javax.swing.JButton carsButton;
    private javax.swing.JButton customersButton;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JButton homepageButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton rentalDetailButton;
    // End of variables declaration//GEN-END:variables

 private void carsPanel(){
        detailPanel.removeAll();
        CarsPanel carPanel =new CarsPanel();
         carPanel.setSize(detailPanel.getWidth(), detailPanel.getHeight());
         detailPanel.add(carPanel);
        detailPanel.repaint();
        detailPanel.revalidate();     

//         HomePage homePanel =new HomePage();
//         homePanel.setVisible(true);
//         this.dispose();

    }
 
 private void carTypePanel(){
      detailPanel.removeAll();
        CarTypePanel cartypePanel =new CarTypePanel();
        cartypePanel.setSize(detailPanel.getWidth(), detailPanel.getHeight());
        detailPanel.add(cartypePanel);
        detailPanel.repaint();
        detailPanel.revalidate();
 }
 
 private void customerPanel(){
        detailPanel.removeAll();
       CustomerPanel customerPanel =new CustomerPanel();
       customerPanel.setSize(detailPanel.getWidth(), detailPanel.getHeight());
       detailPanel.add(customerPanel);
       detailPanel.repaint();
       detailPanel.revalidate();
 }
 
  private void bookingPanel(){
        detailPanel.removeAll();
       CarBorrowPanel bookingPanel =new CarBorrowPanel();
       bookingPanel.setSize(detailPanel.getWidth(), detailPanel.getHeight());
       detailPanel.add(bookingPanel);
       detailPanel.repaint();
       detailPanel.revalidate();
 }
 
 private void loadHomePage(){
           this.setVisible(false);
           ViewNavigator.getInstance().disposeAdminFrame();
           ViewNavigator.getInstance().visibleMainFrame();
 }






}
