/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package carrentapplication.view;

import carrentapplication.controller.CheckOverDueController;
import carrentapplication.controller.RentalDetailController;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manidu
 */
public class CarBorrowPanel extends javax.swing.JPanel {
         private RentalDetailController rentDetailController;
         private CheckOverDueController overDueController;
    /**
     * Creates new form BookingPanel
     */
    public CarBorrowPanel() {
        this.rentDetailController =new RentalDetailController();
        this.overDueController =new CheckOverDueController();
        initComponents();
        loadAllRentdetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        customeRentDetailTable = new javax.swing.JTable();
        filterButton = new javax.swing.JButton();
        filterComboBox = new javax.swing.JComboBox<>();
        stateTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        orderIDTextField = new javax.swing.JTextField();
        currentTotalTextField = new javax.swing.JTextField();
        advanceTextField = new javax.swing.JTextField();
        overDueTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        fromTextField = new javax.swing.JTextField();
        toDateTextField = new javax.swing.JTextField();
        overDueButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        remainAmountTextField = new javax.swing.JTextField();
        borrowCarButton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        hourlyRateTextField = new javax.swing.JTextField();
        dailyRateTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel1011 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        customeRentDetailTable.setBackground(new java.awt.Color(255, 204, 204));
        customeRentDetailTable.setForeground(new java.awt.Color(0, 0, 0));
        customeRentDetailTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        customeRentDetailTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                customeRentDetailTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(customeRentDetailTable);

        filterButton.setBackground(new java.awt.Color(153, 0, 255));
        filterButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        filterButton.setForeground(new java.awt.Color(0, 0, 0));
        filterButton.setText("Filter");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        filterComboBox.setBackground(new java.awt.Color(255, 102, 102));
        filterComboBox.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        filterComboBox.setForeground(new java.awt.Color(0, 0, 0));
        filterComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Current" }));
        filterComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterComboBoxActionPerformed(evt);
            }
        });

        stateTextField.setBackground(new java.awt.Color(204, 153, 255));
        stateTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        stateTextField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("order id ");

        jLabel2.setBackground(new java.awt.Color(0, 153, 204));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Current Total");

        jLabel4.setBackground(new java.awt.Color(0, 153, 204));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 153));
        jLabel4.setText("Advance");

        orderIDTextField.setBackground(new java.awt.Color(0, 204, 255));
        orderIDTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        orderIDTextField.setForeground(new java.awt.Color(0, 0, 0));

        currentTotalTextField.setBackground(new java.awt.Color(0, 204, 255));
        currentTotalTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        currentTotalTextField.setForeground(new java.awt.Color(0, 0, 0));

        advanceTextField.setBackground(new java.awt.Color(0, 204, 255));
        advanceTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        advanceTextField.setForeground(new java.awt.Color(0, 0, 0));

        overDueTextField.setBackground(new java.awt.Color(0, 204, 255));
        overDueTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        overDueTextField.setForeground(new java.awt.Color(0, 0, 0));
        overDueTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overDueTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(0, 153, 204));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("toDate");

        jLabel6.setBackground(new java.awt.Color(0, 153, 204));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText("fromDate");

        fromTextField.setBackground(new java.awt.Color(0, 204, 255));
        fromTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fromTextField.setForeground(new java.awt.Color(0, 0, 0));

        toDateTextField.setBackground(new java.awt.Color(0, 204, 255));
        toDateTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        toDateTextField.setForeground(new java.awt.Color(0, 0, 0));

        overDueButton.setBackground(new java.awt.Color(153, 0, 255));
        overDueButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        overDueButton.setForeground(new java.awt.Color(0, 0, 0));
        overDueButton.setText("Check OverDue");
        overDueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                overDueButtonActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(0, 153, 204));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 153));
        jLabel7.setText("Daily Rate");

        remainAmountTextField.setBackground(new java.awt.Color(0, 204, 255));
        remainAmountTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        remainAmountTextField.setForeground(new java.awt.Color(0, 0, 0));
        remainAmountTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remainAmountTextFieldActionPerformed(evt);
            }
        });

        borrowCarButton.setBackground(new java.awt.Color(255, 51, 51));
        borrowCarButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        borrowCarButton.setForeground(new java.awt.Color(0, 0, 0));
        borrowCarButton.setText("Borrow Car");
        borrowCarButton.setToolTipText("");
        borrowCarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrowCarButtonActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(0, 153, 204));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 153));
        jLabel8.setText("Remain Amount");

        jLabel9.setBackground(new java.awt.Color(0, 153, 204));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 153));
        jLabel9.setText("Hourly Rate");

        hourlyRateTextField.setBackground(new java.awt.Color(0, 204, 255));
        hourlyRateTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        hourlyRateTextField.setForeground(new java.awt.Color(0, 0, 0));
        hourlyRateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hourlyRateTextFieldActionPerformed(evt);
            }
        });

        dailyRateTextField.setBackground(new java.awt.Color(0, 204, 255));
        dailyRateTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        dailyRateTextField.setForeground(new java.awt.Color(0, 0, 0));
        dailyRateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dailyRateTextFieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("If remain <0 Back pay for Customer");
        jLabel3.setToolTipText("");

        jLabel1011.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1011.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1011.setText("If remain >0 due pay from customer");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                        .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(filterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(615, 615, 615))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(orderIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(advanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hourlyRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dailyRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(129, 129, 129)
                                .addComponent(borrowCarButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(toDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(overDueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(overDueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(currentTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(remainAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1011, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(filterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(orderIDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dailyRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(borrowCarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentTotalTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hourlyRateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advanceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fromTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(toDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overDueButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(overDueTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(remainAmountTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1011, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(64, 64, 64))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void filterComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterComboBoxActionPerformed
          stateTextField.setText(filterComboBox.getSelectedItem().toString());
    }//GEN-LAST:event_filterComboBoxActionPerformed

    private void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filterButtonActionPerformed
       addToTable();
    }//GEN-LAST:event_filterButtonActionPerformed

    private void overDueTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overDueTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_overDueTextFieldActionPerformed

    private void overDueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_overDueButtonActionPerformed
          checkOverDue();
    }//GEN-LAST:event_overDueButtonActionPerformed

    private void remainAmountTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remainAmountTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_remainAmountTextFieldActionPerformed

    private void borrowCarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrowCarButtonActionPerformed
          borrowCar();
    }//GEN-LAST:event_borrowCarButtonActionPerformed

    private void customeRentDetailTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_customeRentDetailTableMouseClicked
               orderIDTextField.setText(String.valueOf(customeRentDetailTable.getValueAt(customeRentDetailTable.getSelectedRow(), 2)));
               currentTotalTextField.setText(String.valueOf(customeRentDetailTable.getValueAt(customeRentDetailTable.getSelectedRow(), 6)));
               advanceTextField.setText(String.valueOf(customeRentDetailTable.getValueAt(customeRentDetailTable.getSelectedRow(), 7)));
               fromTextField.setText(String.valueOf(customeRentDetailTable.getValueAt(customeRentDetailTable.getSelectedRow(), 4)));
               toDateTextField.setText(String.valueOf(customeRentDetailTable.getValueAt(customeRentDetailTable.getSelectedRow(), 5)));
               dailyRateTextField.setText(String.valueOf(customeRentDetailTable.getValueAt(customeRentDetailTable.getSelectedRow(), 8)));
               hourlyRateTextField.setText(String.valueOf(customeRentDetailTable.getValueAt(customeRentDetailTable.getSelectedRow(), 9)));
    }//GEN-LAST:event_customeRentDetailTableMouseClicked

    private void hourlyRateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hourlyRateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hourlyRateTextFieldActionPerformed

    private void dailyRateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dailyRateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dailyRateTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField advanceTextField;
    private javax.swing.JButton borrowCarButton;
    private javax.swing.JTextField currentTotalTextField;
    private javax.swing.JTable customeRentDetailTable;
    private javax.swing.JTextField dailyRateTextField;
    private javax.swing.JButton filterButton;
    private javax.swing.JComboBox<String> filterComboBox;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JTextField hourlyRateTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1011;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField orderIDTextField;
    private javax.swing.JButton overDueButton;
    private javax.swing.JTextField overDueTextField;
    private javax.swing.JTextField remainAmountTextField;
    private javax.swing.JTextField stateTextField;
    private javax.swing.JTextField toDateTextField;
    // End of variables declaration//GEN-END:variables


private void loadAllRentdetails(){
    String[] columns ={"custID","rentID","orderdetailID","model","fromDate","toDate","total","advance","d.rate","h.rate","overdue"};
    DefaultTableModel dtm =new DefaultTableModel(columns,0){
            @Override
            public boolean isCellEditable(int row,int column){
                   return false;
            }     
        
    };
    customeRentDetailTable.setModel(dtm);
    
}


private void addToTable(){
    try {
          String state =stateTextField.getText();
    List<Object[]> tabledata =rentDetailController.getAllRentDetail(state);
        DefaultTableModel dtm =   (DefaultTableModel) customeRentDetailTable.getModel();
     for(Object[] rawdata : tabledata){
           System.out.println(Arrays.toString(rawdata));
            dtm.addRow(rawdata);
       }
      
    } catch (Exception e) {
         JOptionPane.showConfirmDialog(this, e.getMessage());
    }  
}

private void checkOverDue(){
    
    try{
         Double total =Double.valueOf(currentTotalTextField.getText());
    Double advance =Double.valueOf(advanceTextField.getText());
    Double dailyRate =Double.valueOf(dailyRateTextField.getText());
    Double hourRate =Double.valueOf(hourlyRateTextField.getText());
    DateTimeFormatter formatter =DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.S");
    LocalDateTime fromDate =LocalDateTime.parse(fromTextField.getText(),formatter);
    LocalDateTime toDate =LocalDateTime.parse(toDateTextField.getText(), formatter);
    
    Double overDue =overDueController.getOverDue(fromDate, toDate, dailyRate, hourRate, total, advance);
    // overDueTextField.setText(String.valueOf(overDue));
     
     Double remainAmount =(total+overDue)-advance;
     overDue =(remainAmount<0) ? (overDue+remainAmount) : overDue;
     remainAmountTextField.setText(String.valueOf(remainAmount));
      overDueTextField.setText(String.valueOf(overDue));
    
        } catch (Exception e) {
         JOptionPane.showConfirmDialog(this, e.getMessage());
    } 
  
}

private void borrowCar(){
       try {
         boolean state =rentDetailController.borrowCar(Integer.valueOf(orderIDTextField.getText()), true, Double.valueOf(overDueTextField.getText()));
     if(state){
         JOptionPane.showConfirmDialog(this, "car borrow Successfully");
         loadAllRentdetails();
         addToTable();
     }   else {
         JOptionPane.showConfirmDialog(this, " car doesnot borrow");
     }
    } catch (Exception e) {
    }
}





}
