/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package carrentapplication.view;

import carrentapplication.controller.CarController;
import carrentapplication.controller.CarTypeController;
import carrentapplication.dto.CarDto;
import java.time.Year;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import  javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manidu
 */
public class CarsPanel extends javax.swing.JPanel {
        private CarTypeController carTypeController;
        private CarController carController;
        private boolean airBag;
    /**
     * Creates new form CarsPanel
     */
    public CarsPanel() {
         carTypeController =new CarTypeController();
         carController =new CarController();
        initComponents();      
        loadCarTypes();
        clearText();
        loadAllCars();
        
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        carTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        v_noLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        modelLabel = new javax.swing.JLabel();
        brandLabel = new javax.swing.JLabel();
        yearLabel = new javax.swing.JLabel();
        modelTextField = new javax.swing.JTextField();
        v_noTextField = new javax.swing.JTextField();
        brandTextField = new javax.swing.JTextField();
        idTextField = new javax.swing.JTextField();
        yearTextField = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();
        carTypeLabel = new javax.swing.JLabel();
        carTypeTextField = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        colourLabel = new javax.swing.JLabel();
        colourTextField = new javax.swing.JTextField();
        sheetLabel = new javax.swing.JLabel();
        sheetTextField = new javax.swing.JTextField();
        bagLabel = new javax.swing.JLabel();
        fuelTypeLabel = new javax.swing.JLabel();
        falseRadioButton = new javax.swing.JRadioButton();
        trueRadioButton = new javax.swing.JRadioButton();
        fuelTypeTextField = new javax.swing.JTextField();
        airBagTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        carTable.setBackground(new java.awt.Color(204, 255, 204));
        carTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        carTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(carTable);

        jPanel2.setBackground(new java.awt.Color(153, 0, 255));

        v_noLabel.setBackground(new java.awt.Color(255, 51, 51));
        v_noLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        v_noLabel.setForeground(new java.awt.Color(0, 0, 0));
        v_noLabel.setText("V_No");

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Car ID");

        modelLabel.setBackground(new java.awt.Color(255, 51, 51));
        modelLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        modelLabel.setForeground(new java.awt.Color(0, 0, 0));
        modelLabel.setText("Model");

        brandLabel.setBackground(new java.awt.Color(255, 51, 51));
        brandLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        brandLabel.setForeground(new java.awt.Color(0, 0, 0));
        brandLabel.setText("Brand");

        yearLabel.setBackground(new java.awt.Color(255, 51, 51));
        yearLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        yearLabel.setForeground(new java.awt.Color(0, 0, 0));
        yearLabel.setText("Year");

        modelTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        modelTextField.setForeground(new java.awt.Color(0, 0, 0));

        v_noTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        v_noTextField.setForeground(new java.awt.Color(0, 0, 0));

        brandTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        brandTextField.setForeground(new java.awt.Color(0, 0, 0));

        idTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        idTextField.setForeground(new java.awt.Color(0, 0, 0));

        yearTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        yearTextField.setForeground(new java.awt.Color(0, 0, 0));
        yearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearTextFieldActionPerformed(evt);
            }
        });

        saveButton.setBackground(new java.awt.Color(0, 255, 102));
        saveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveButton.setForeground(new java.awt.Color(0, 0, 0));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        updateButton.setBackground(new java.awt.Color(0, 255, 102));
        updateButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        updateButton.setForeground(new java.awt.Color(0, 0, 0));
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setBackground(new java.awt.Color(0, 255, 102));
        deleteButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        deleteButton.setForeground(new java.awt.Color(0, 0, 0));
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        carTypeLabel.setBackground(new java.awt.Color(255, 51, 51));
        carTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        carTypeLabel.setForeground(new java.awt.Color(0, 0, 0));
        carTypeLabel.setText("Car Type");

        carTypeTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        carTypeTextField.setForeground(new java.awt.Color(0, 0, 0));

        jComboBox1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "*" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(0, 0, 0));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "PETROL", "DIESEL" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        colourLabel.setBackground(new java.awt.Color(255, 51, 51));
        colourLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        colourLabel.setForeground(new java.awt.Color(0, 0, 0));
        colourLabel.setText("Colour");

        colourTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        colourTextField.setForeground(new java.awt.Color(0, 0, 0));

        sheetLabel.setBackground(new java.awt.Color(255, 51, 51));
        sheetLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        sheetLabel.setForeground(new java.awt.Color(0, 0, 0));
        sheetLabel.setText("No_sheets");

        sheetTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        sheetTextField.setForeground(new java.awt.Color(0, 0, 0));

        bagLabel.setBackground(new java.awt.Color(255, 51, 51));
        bagLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        bagLabel.setForeground(new java.awt.Color(0, 0, 0));
        bagLabel.setText("Air Bags");

        fuelTypeLabel.setBackground(new java.awt.Color(255, 51, 51));
        fuelTypeLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        fuelTypeLabel.setForeground(new java.awt.Color(0, 0, 0));
        fuelTypeLabel.setText("Fuel Type");

        buttonGroup1.add(falseRadioButton);
        falseRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        falseRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        falseRadioButton.setText("Have not");
        falseRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                falseRadioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(trueRadioButton);
        trueRadioButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        trueRadioButton.setForeground(new java.awt.Color(0, 0, 0));
        trueRadioButton.setText("Have");
        trueRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trueRadioButtonActionPerformed(evt);
            }
        });

        fuelTypeTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        fuelTypeTextField.setForeground(new java.awt.Color(0, 0, 0));

        airBagTextField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        airBagTextField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("ex : sp-QL-1234");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(90, 90, 90)
                                .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(v_noLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modelTextField)
                                    .addComponent(v_noTextField)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(brandLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(brandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(colourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(90, 90, 90)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(colourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(saveButton)
                                    .addComponent(updateButton)
                                    .addComponent(deleteButton)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(fuelTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(bagLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(trueRadioButton)
                                .addGap(22, 22, 22)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(falseRadioButton)
                                .addGap(18, 18, 18)
                                .addComponent(airBagTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(fuelTypeTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(carTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(sheetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sheetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(carTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(v_noLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(v_noTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(modelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modelTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(brandTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7))
                    .addComponent(brandLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(updateButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(colourLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(colourTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(saveButton))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(yearLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sheetLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sheetTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(carTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(carTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fuelTypeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fuelTypeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bagLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(falseRadioButton)
                        .addComponent(trueRadioButton)
                        .addComponent(airBagTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
          //genderTextField.setText(jComboBox1.getSelectedItem().toString());
          carTypeTextField.setText(jComboBox1.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        deleteCar();
    }//GEN-LAST:event_deleteButtonActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        fuelTypeTextField.setText(jComboBox2.getSelectedItem().toString());
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void yearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearTextFieldActionPerformed

    private void trueRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trueRadioButtonActionPerformed
        this.airBag =true;
    }//GEN-LAST:event_trueRadioButtonActionPerformed

    private void falseRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_falseRadioButtonActionPerformed
        this.airBag =false;
    }//GEN-LAST:event_falseRadioButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
       addCar();
    }//GEN-LAST:event_saveButtonActionPerformed

    private void carTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carTableMouseClicked
         searchCar();
    }//GEN-LAST:event_carTableMouseClicked

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
      updateCar();
    }//GEN-LAST:event_updateButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airBagTextField;
    private javax.swing.JLabel bagLabel;
    private javax.swing.JLabel brandLabel;
    private javax.swing.JTextField brandTextField;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTable carTable;
    private javax.swing.JLabel carTypeLabel;
    private javax.swing.JTextField carTypeTextField;
    private javax.swing.JLabel colourLabel;
    private javax.swing.JTextField colourTextField;
    private javax.swing.JButton deleteButton;
    private javax.swing.JRadioButton falseRadioButton;
    private javax.swing.JLabel fuelTypeLabel;
    private javax.swing.JTextField fuelTypeTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JTextField modelTextField;
    private javax.swing.JButton saveButton;
    private javax.swing.JLabel sheetLabel;
    private javax.swing.JTextField sheetTextField;
    private javax.swing.JRadioButton trueRadioButton;
    private javax.swing.JButton updateButton;
    private javax.swing.JLabel v_noLabel;
    private javax.swing.JTextField v_noTextField;
    private javax.swing.JLabel yearLabel;
    private javax.swing.JTextField yearTextField;
    // End of variables declaration//GEN-END:variables

    private void clearText(){
           idTextField.setText("");
           v_noTextField.setText("");
           brandTextField.setText("");
           modelTextField.setText("");
           colourTextField.setText("");
           sheetTextField.setText("");
           fuelTypeTextField.setText("");        
           airBagTextField.setText("");
           yearTextField.setText("");
    }
    
    
    
    
private void loadCarTypes(){
    try {
         List<String> carTypes =carTypeController.getCategories();
      //   jComboBox1.removeAllItems();
         for(String carType : carTypes){
                jComboBox1.addItem(carType);
         }
         
    } catch (Exception e) {
        e.printStackTrace();
    }
         
}

private void loadAllCars(){
          try {
          String columns[] ={"id","V_No","model","fuel"};
      DefaultTableModel dtm =new DefaultTableModel(columns,0){
            public boolean isCellEditable(int row, int column){
                     return false;
            }
      };
      
      carTable.setModel(dtm);
      ArrayList<CarDto> cardtoes =carController.getAllCars();
      for(CarDto dto : cardtoes){
             Object[] carData ={dto.getId(),dto.getV_No(),dto.getModel(),dto.getFuelType()};
              dtm.addRow(carData);         
      }
         
         
     } catch (Exception e) {
         JOptionPane.showConfirmDialog(this, e.getMessage());
     }    
    
    
    
}

private void searchCar(){
      try {
          String id =carTable.getValueAt(carTable.getSelectedRow(), 0).toString();
          CarDto dto =carController.getCar(id);
          idTextField.setText(String.valueOf(dto.getId()));
           v_noTextField.setText(dto.getV_No());
           brandTextField.setText(dto.getBrand());
           modelTextField.setText(dto.getModel());
           colourTextField.setText(dto.getColor());
           sheetTextField.setText(String.valueOf(dto.getNum_ofsheets()));
           carTypeTextField.setText(dto.getCarType());
           fuelTypeTextField.setText(dto.getFuelType());        
           airBagTextField.setText(String.valueOf(dto.isAirBags()));
           yearTextField.setText(dto.getYear().toString());
          
    } catch (Exception e) {
          JOptionPane.showConfirmDialog(this, e.getMessage());
    }
        
    
   
}

private void addCar(){
    
    try {
        
        CarDto carDto =new CarDto(v_noTextField.getText(),
              modelTextField.getText(),
              brandTextField.getText(),
              colourTextField.getText(),
              Integer.valueOf(sheetTextField.getText()),
              fuelTypeTextField.getText(),
              this.airBag,
              Year.parse(yearTextField.getText()) );
      String carType =carTypeTextField.getText();
      Integer id =carController.addCar(carDto, carType);
      if(id>0){
          JOptionPane.showConfirmDialog(this, "save sucessfully");
          clearText();
          loadAllCars();
      }   else{
          JOptionPane.showConfirmDialog(this, "does not sucessfully");
      }
        
    } catch (Exception e) {
         JOptionPane.showConfirmDialog(this, e.getMessage());
    }
      
      
}

private void updateCar(){
    try{
    CarDto dto =new CarDto(Integer.valueOf(idTextField.getText()),
            v_noTextField.getText(),
            modelTextField.getText(),
            brandTextField.getText(),
            colourTextField.getText(),
            Integer.valueOf(sheetTextField.getText()),
            fuelTypeTextField.getText(),
            this.airBag,
            Year.parse(yearTextField.getText()),
            carTypeTextField.getText());
    
       boolean result =carController.updateCar(dto);
        if(result){
          JOptionPane.showConfirmDialog(this, "update sucessfully");
          clearText();
          loadAllCars();
      }   else{
          JOptionPane.showConfirmDialog(this, "does not update sucessfully");
      }
        
    
        
    } catch (Exception e) {
         JOptionPane.showConfirmDialog(this, e.getMessage());
    }
   
}

private void deleteCar(){

        try{
               String id =idTextField.getText();
    
       boolean result =carController.deleteCar(id);
        if(result){
          JOptionPane.showConfirmDialog(this, "delete sucessfully");
          clearText();
          loadAllCars();
      }   else{
          JOptionPane.showConfirmDialog(this, "does not delete sucessfully");
      }
 
           } catch (Exception e) {
         JOptionPane.showConfirmDialog(this, e.getMessage());
           }

}

}